[build]
builder = "DOCKERFILE"
dockerfilePath = "packages/api/Dockerfile"

[deploy]
startCommand = "node packages/api/dist/main.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
