[build]
builder = "DOCKERFILE"
dockerfilePath = "packages/web/Dockerfile"

[deploy]
startCommand = "serve -s dist -l 3000 --no-clipboard"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
